### ISSUE TITLE
plumber --version is `UNSET`

### ISSUE THREAD

**Issue by a-n-n-a-l-e-e** [streamdal/plumber#363]
**Describe the bug**
```console
./plumber --version
UNSET
```

[go.mod](https://github.com/streamdal/plumber/blob/90ee8c815f6dec674dd51602332012d83827f4f5/go.mod#L1C1-L1C36) sets `module github.com/batchcorp/plumber` but the [Makefile](https://github.com/streamdal/plumber/blob/90ee8c815f6dec674dd51602332012d83827f4f5/Makefile#L9) uses `-X 'github.com/streamdal/plumber/options.VERSION=${VERSION}'`

**Comment by blinktag** [comment]
We renamed our company from Batch.sh to Streamdal but haven't gotten around to updating all of our source packages yet. Will get working on that shortly. The version should also include the version number like `v2.4.0-854d258`, but that is currently only set via CI, so we'll work on a solution for that also

**Comment by blinktag** [comment]
@a-n-n-a-l-e-e this is fixed now. The CI process will inject the version into version.txt and then running the make build commands will pull this version in
