### ISSUE TITLE
Seg vault of v2.x on older linux and macos distributions

### ISSUE THREAD

**Issue by seanogor** [streamdal/plumber#367]
**Describe the bug**
Seg fault occurs in linux/darwin builds in 2.x version

**To Reproduce**
Run plumber in ubuntu 20.04 LTS 

**Expected behavior**
Work as expected when reading rabbitmq queue:

Encountered running:
```
plumber read rabbit ...

exception:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17cf[6]]

goroutine 1 [running]:
main.readFromStdin(0xc000[7](
repo./7979469044/job/21786937627#step:5:8)e5e00)
	/home/runner/work/plumber/plumber/main.go:17[8]
(repo/7979469044/job/21786937627#step:5:9) +0x2d3
main.main()
	/home/runner/work/plumber/plumber/main.go:40 +0xcf
Error: Process completed with exit code 2.
```

**CLI (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04
**Additional context**
I love this tool, you guys are awesome. I worked around this issue by using a version released closer to the OS release that supported the functionality I needed (v1.0.3)... I'm sure this may be expected behaviour with breaking changes in logic between major versions, just want to share it for completeness. Thank you so much for your incredible, generic tool

**Comment by blinktag** [comment]
>I love this tool, you guys are awesome
Glad to hear! Thank you 😃 
Your issue should be fixed in https://github.com/streamdal/plumber/releases/tag/v2.5.4
Let me know if you run into any more trouble
